Update outlook_analyzer.py w/ clean code
lisashub/outlookanalyzer pull request #19
Opened 2022-04-18 01:58 UTC by tingjlee

Just added the clean code at the end of everything.

2022-04-18 02:25 UTC, cplummer-uwm requested changes

2022-04-18 02:25 UTC, cplummer-uwm commented on outlook_analyzer.py
> +            for item in DIR_LIST:
You should create a new folder in C:\WINDOWS\Temp for outlookanalyzer and only clean the files in that directory. If you clean all the files with .txt/.png/.jpg, you might be breaking some other program that is using those files.

2022-04-18 02:25 UTC, cplummer-uwm commented on outlook_analyzer.py
> +DIR_LIST = os.listdir(TEMP_DIR) # Puts Temp directory as a list
You should update TEMP_DIR above to be a folder unique to us and create it if it doesn't exist.

2022-04-18 21:47 UTC, lisashub commented on outlook_analyzer.py
> +            for item in DIR_LIST:
My bad, if you got an email ping with my previous comment. Thought for a hot second that using the TEMP directory was breaking something for Ting, but apparently not?

2022-04-18 22:30 UTC, cplummer-uwm commented on outlook_analyzer.py
> +            for item in DIR_LIST:
Not sure yet where the "issue" is or even if there is a problem. Using a temp location is a best practices for temp files. See https://softwareengineering.stackexchange.com/questions/314796/should-temporary-files-be-saved-to-tmp-or-the-current-working-directory

2022-04-18 23:49 UTC, lisashub commented on outlook_analyzer.py
> +            for item in DIR_LIST:
Yes, I'd mentioned in my previous comment that I _thought_ there was an issue, but apparently there isn't one, haha. I'd made a previous comment (now deleted) based on my first impression. My existing comment is a heads up that the now deleted comment was made in error; I know GitHub sends email summaries.

2022-04-22 06:40 UTC, cplummer-uwm commented
Closing this PR since this code was integrated into my branch. Thanks for the ideas.

2022-04-22 06:40 UTC, cplummer-uwm commented
Closing this PR since this code was integrated into my branch. Thanks for the ideas.

2022-04-22 06:40 UTC, closed without merging