Adding important email metric and other fixes
lisashub/outlookanalyzer pull request #20
Opened 2022-04-18 02:04 UTC by cplummer-uwm

This is incremental development...
1. The image generation is not perfect yet (I would like to argue it is not needed for text only)
2. There is some repetitive code that I think can be combined into a function later

2022-04-18 21:27 UTC, lisashub requested changes

2022-04-18 21:27 UTC, lisashub commented on outlook_analyzer.py
> +        if (item.Importance == 2 and item.Class == 43):
Nice job IDing the field that indicates importance! Would you be willing to add a comment somewhere that MailItem.Importance == 2 indicates a "High" importance flag and MailItem.Class == 43 indicates a MailItem (as opposed to a meeting invite)? 

As part of technical documentation, I'd like to suggest in our team meeting a wave of code comment revisions and additions so interested parties can more readily understand variables/properties/value meanings throughout the program.

2022-04-18 21:27 UTC, lisashub commented on outlook_analyzer.py
> +                subject = [clean_subject.encode("utf-8").strip()] # Common for subjects to have emoji or utf8 data so need encode as utf8
May make more sense to move Line 155 into the cleanup() function since it seems to also be a cleanup step. Doing so would also appear to remove the need for Line 217.

2022-04-18 21:27 UTC, lisashub commented on outlook_analyzer.py
> +IMPORTANT_EMAIL_DATA_FILE_NAME = TEMP_DIR + "\\" + TIME_STR + "_" + "important_email.txt"
Are these variables still needed if we go the data image route? (Line 26, Line 27)

2022-04-18 21:27 UTC, lisashub commented on outlook_analyzer.py
> +def generic_email_data_gen(messages_list, email_data_file):
Thinking it makes more sense to rename this function after the metrics it actually handles (i.e. flagged/important), rather than "generic".

2022-04-18 22:14 UTC, cplummer-uwm commented on outlook_analyzer.py
> +def generic_email_data_gen(messages_list, email_data_file):
I don't agree, I specifically did not name it after flagged/important because It could potentially handle more than flagged/important and there is nothing in the code specific to flagged/important so it should not be named after those.

2022-04-18 22:17 UTC, cplummer-uwm commented on outlook_analyzer.py
> +IMPORTANT_EMAIL_DATA_FILE_NAME = TEMP_DIR + "\\" + TIME_STR + "_" + "important_email.txt"
Not sure what you are asking exactly, the only reason I am using text files is because the encoding of ut8 data become binary data and trying to go directly from an in-memory data frame to an image is not ideal because python adds a b' in front of each string which is confusing so I have to decode and write it do a text file and then create the data frame from the decoded text string. See here: https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal

2022-04-18 22:18 UTC, cplummer-uwm commented on outlook_analyzer.py
> +IMPORTANT_EMAIL_DATA_FILE_NAME = TEMP_DIR + "\\" + TIME_STR + "_" + "important_email.txt"
I don't want to generate an image off of this data and I want to go straight to PDF so it would be the IMAGE DATA FILE that I want to remove.

2022-04-18 22:19 UTC, cplummer-uwm commented on outlook_analyzer.py
> +                subject = [clean_subject.encode("utf-8").strip()] # Common for subjects to have emoji or utf8 data so need encode as utf8
This is not a cleanup step, it is the step for encoding into ut8. Doesn't make sense to move that into the cleanup function.

2022-04-18 22:20 UTC, cplummer-uwm commented on outlook_analyzer.py
> +        if (item.Importance == 2 and item.Class == 43):
Yes, I can add a comment in there.

2022-04-18 23:18 UTC, lisashub commented on outlook_analyzer.py
> +IMPORTANT_EMAIL_DATA_FILE_NAME = TEMP_DIR + "\\" + TIME_STR + "_" + "important_email.txt"
Thanks for your responses! From your first message, I was able to answer my question. Sorry if it was unclear.

So my understanding is that if we don't generate your features' data frames directly to an image and instead generate into separate PDFs, Ting will need to use an entirely new package to merge the PDFs (per his latest message in Teams). This would seem to essentially nullify all the learning and work he's already done in the current PDF generation. I'm actually dual tasking while reviewing - considering alternative solutions that harmonize with Ting's efforts while also orienting myself with your code. 

In the generate_generic_viz function, I can produce a legible data frame image if I replace the line "plt.savefig(email_image_file, dpi=150)" with "dfi.export(df, email_image_file)". Believe Ting would be able to use what's produced with his current solution and continue building on top of the work he's already done in creating the dashboard.  I'm wondering why we wouldn't go with this solution. What are your thoughts?

2022-04-18 23:57 UTC, lisashub commented on outlook_analyzer.py
> +                subject = [clean_subject.encode("utf-8").strip()] # Common for subjects to have emoji or utf8 data so need encode as utf8
Okay. In the data analysis world, we sometimes use "cleaning" to also mean encoding/reformatting data in general so it can be analyzed: https://www.tableau.com/learn/articles/what-is-data-cleaning

I'm fine with leaving the the script as-is, though.

2022-04-19 00:00 UTC, lisashub commented on outlook_analyzer.py
> +def generic_email_data_gen(messages_list, email_data_file):
Could potentially be used, but since we're wrapping up any major feature work this week my thought was that we won't be doing major refactors. I'm fine leaving it if you have strong feelings about it, though. Not that major.

2022-04-19 01:43 UTC, lisashub approved these changes

2022-04-19 01:44 UTC, merged