Docstring updates
lisashub/outlookanalyzer pull request #28
Opened 2022-04-26 13:34 UTC by lisashub

2022-04-26 19:47 UTC, cplummer-uwm approved these changes

2022-04-26 20:58 UTC, cplummer-uwm requested changes

2022-04-26 20:58 UTC, cplummer-uwm commented on outlook_analyzer.py
> +                if (inbox_item.UnRead == True):
If you are going to repeat this code, it should be in a function instead of the same code copied from above
https://www.youtube.com/watch?v=hRBtws2n1XQ

2022-04-26 20:58 UTC, cplummer-uwm commented on outlook_analyzer.py
>              if os.path.isfile(path):
Are you going to change this to s.path.isdir?

2022-04-26 21:14 UTC, lisashub commented on outlook_analyzer.py
> +                if (inbox_item.UnRead == True):
Decided to instead take out the attempt to finish the loop entirely and add some error text that advises the user to rerun for accurate unread/read data.

2022-04-26 21:17 UTC, lisashub commented on outlook_analyzer.py
>              if os.path.isfile(path):
Wasn't planning it since, after double-checking, the functionality appears the same.

2022-04-26 21:26 UTC, cplummer-uwm commented on outlook_analyzer.py
>              if os.path.isfile(path):
you can see the different like this:
```
import os

path = os.environ['USERPROFILE']+"\AppData\Local\Temp\gen_py"

if os.path.isfile(path):
    print("I am file. This is will never get run.")

if os.path.isdir(path):
    print("I am dir.")
```

2022-04-26 21:29 UTC, lisashub commented on outlook_analyzer.py
>              if os.path.isfile(path):
Wow, my double checking sucked.

This has been updated in a recent commit.

2022-04-26 21:34 UTC, cplummer-uwm commented on outlook_analyzer.py
> +                for module in system_modules:
I'm getting this error forcing an exception or running this code on its own. Is there something additional to install for this to work?
```
Traceback (most recent call last):
  File "c:\Users\churn\Documents\GitHub\outlookanalyzer\test.py", line 29, in <module>
    system_modules = [module.__name__ for module in sys.module.values]
AttributeError: module 'sys' has no attribute 'module'. Did you mean: 'modules'?
```

2022-04-26 21:40 UTC, cplummer-uwm commented on outlook_analyzer.py
>              if os.path.isfile(path):
My spelling sucks. haha

2022-04-26 22:11 UTC, lisashub commented on outlook_analyzer.py
> +                for module in system_modules:
Try:

import re
import sys
import shutil
import os

MODULE_LIST = [m.__name__ for m in sys.modules.values()]
for module in MODULE_LIST:
    if re.match(r'win32com\.gen_py\..+', module):
        del sys.modules[module]
        shutil.rmtree(os.path.join(os.environ.get('LOCALAPPDATA'), 'Temp', 'gen_py'))

system_modules = [module.__name__ for module in  sys.modules.values()]
for module in system_modules:
    print(module)

2022-04-26 22:50 UTC, cplummer-uwm commented on outlook_analyzer.py
> +                for module in system_modules:
```
import re
import sys
import shutil
import os

MODULE_LIST = [m.name for m in sys.modules.values()]
for module in MODULE_LIST:
    if re.match(r'win32com.gen_py..+', module):
        del sys.modules[module]
        shutil.rmtree(os.path.join(os.environ.get('LOCALAPPDATA'), 'Temp', 'gen_py'))

system_modules = [module.name for module in sys.modules.values()]
for module in system_modules:
    print(module)
```
results in
```
Traceback (most recent call last):
  File "c:\Users\churn\Documents\GitHub\outlookanalyzer\test.py", line 41, in <module>
    MODULE_LIST = [m.name for m in sys.modules.values()]
  File "c:\Users\churn\Documents\GitHub\outlookanalyzer\test.py", line 41, in <listcomp>
    MODULE_LIST = [m.name for m in sys.modules.values()]
AttributeError: module 'sys' has no attribute 'name'
```

2022-04-28 16:31 UTC, cplummer-uwm approved these changes

2022-04-28 18:52 UTC, merged